# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'finalGanttProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for finalGanttProject
	pod ‘SpreadsheetView’
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'SwiftyRSA'
	pod 'PopupDialog', '~> 0.7'
	

end
